name: Upload Images

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v2

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: smart-climate-lab/mobility_harbach
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-repo

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r private-repo/requirements.txt
    - name: Run script
      run: python private-repo/Main_harbach.py

    - name: Commit and push plot
      run: |
        git config --global user.name 'smart-climate-lab'
        git config --global user.email 'patrick.weiss.klagenfurt@gmail.com'
        git add Crosswalks.png speedometer.png Modal_split.png cars_total.png
        git commit -m "Add generated plot"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        
