name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout public repository
      uses: actions/checkout@v2
    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: smart-climate-lab/dashboard
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-repo
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
      working-directory: private-repo
    - name: Run script
      run: node private-repo/generate_html.js
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
