name: Upload Images

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v2

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: smart-climate-lab/mobility_harbach
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-repo

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r private-repo/requirements.txt

    - name: Run script
      run: python private-repo/Main_harbach.py
          
    - name: Copy images
      run: |
        mkdir -p public-repo/images
        cp private-repo/speedometer.png public-repo/images/
        cp private-repo/Crosswalks.png public-repo/images/
        cp private-repo/Modal_split.png public-repo/images/

    - name: Push public changes
      run: |
        cd public-repo
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update images"
        git push
