name: Generate and Deploy HTML

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht
  workflow_dispatch:      # Ermöglicht manuelle Ausführung

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          path: public-repo

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: smart-climate-lab/mobility_harbach  # Hier private Repository-Namen eintragen
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd private-repo
          pip install -r requirements.txt  # Falls Sie Abhängigkeiten haben

      - name: Generate HTML
        run: |
          cd private-repo
          python generate_html.py  # Ihr Python-Script
          cp index.html ../public-repo/index.html  # Passen Sie den Dateinamen an

      - name: Commit and push changes
        run: |
          cd public-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update HTML content" || echo "No changes to commit"
          git push